# Form implementation generated from reading ui file 'muontra.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from Controller.quanlymuontra import QuanLyMuonTra


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(676, 475)
        Form.setStyleSheet("")
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setGeometry(QtCore.QRect(190, 10, 311, 31))
        self.frame.setStyleSheet("background-color:rgb(170, 170, 255)")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(70, 0, 201, 31))
        self.label_2.setStyleSheet("font: 75 16pt \"Times New Roman\";")
        self.label_2.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.btnAdd = QtWidgets.QPushButton(parent=Form)
        self.btnAdd.setGeometry(QtCore.QRect(140, 420, 61, 31))
        self.btnAdd.setStyleSheet("""
            background-color: rgb(220, 241, 255);
            border: 2px solid rgb(100, 100, 200);
            border-radius: 10px;
            padding: 5px;
            box-shadow: 2px 2px 5px gray;
        """)
        self.btnAdd.setObjectName("btnAdd")
        self.btnXoa = QtWidgets.QPushButton(parent=Form)
        self.btnXoa.setGeometry(QtCore.QRect(450, 420, 61, 31))
        self.btnXoa.setStyleSheet("""
            background-color: rgb(220, 241, 255);
            border: 2px solid rgb(100, 100, 200);
            border-radius: 10px;
            padding: 5px;
            box-shadow: 2px 2px 5px gray;
        """)
        self.btnXoa.setObjectName("btnXoa")
        self.btnSua = QtWidgets.QPushButton(parent=Form)
        self.btnSua.setGeometry(QtCore.QRect(300, 420, 61, 31))
        self.btnSua.setStyleSheet("""
            background-color: rgb(220, 241, 255);
            border: 2px solid rgb(100, 100, 200);
            border-radius: 10px;
            padding: 5px;
            box-shadow: 2px 2px 5px gray;
        """)
        self.btnSua.setObjectName("btnSua")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(0, 40, 671, 161))
        self.widget.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.widget.setObjectName("widget")
        self.label_9 = QtWidgets.QLabel(parent=self.widget)
        self.label_9.setGeometry(QtCore.QRect(30, 30, 111, 21))
        self.label_9.setObjectName("label_9")
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_6.setGeometry(QtCore.QRect(150, 30, 101, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_10 = QtWidgets.QLabel(parent=self.widget)
        self.label_10.setGeometry(QtCore.QRect(30, 70, 71, 21))
        self.label_10.setObjectName("label_10")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(150, 70, 101, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_3.setGeometry(QtCore.QRect(150, 110, 101, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_11 = QtWidgets.QLabel(parent=self.widget)
        self.label_11.setGeometry(QtCore.QRect(30, 110, 71, 21))
        self.label_11.setObjectName("label_11")
        self.comboBox = QtWidgets.QComboBox(parent=self.widget)
        self.comboBox.setGeometry(QtCore.QRect(470, 110, 111, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_14 = QtWidgets.QLabel(parent=self.widget)
        self.label_14.setGeometry(QtCore.QRect(360, 110, 91, 21))
        self.label_14.setObjectName("label_14")
        self.dateEdit_2 = QtWidgets.QDateEdit(parent=self.widget)
        self.dateEdit_2.setGeometry(QtCore.QRect(470, 60, 110, 22))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.label_13 = QtWidgets.QLabel(parent=self.widget)
        self.label_13.setGeometry(QtCore.QRect(360, 60, 101, 21))
        self.label_13.setObjectName("label_13")
        self.dateEdit = QtWidgets.QDateEdit(parent=self.widget)
        self.dateEdit.setGeometry(QtCore.QRect(470, 20, 110, 22))
        self.dateEdit.setObjectName("dateEdit")
        self.label_12 = QtWidgets.QLabel(parent=self.widget)
        self.label_12.setGeometry(QtCore.QRect(360, 20, 91, 21))
        self.label_12.setObjectName("label_12")
        self.tableWidget = QtWidgets.QTableWidget(parent=Form)
        self.tableWidget.setGeometry(QtCore.QRect(0, 200, 671, 191))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.btnAdd.clicked.connect(self.add_mt)
        self.btnXoa.clicked.connect(self.delete_mt)
        self.btnSua.clicked.connect(self.update_mt)
        self.tableWidget.cellClicked.connect(self.cell_click)
        self.load_data()

    def load_data(self):
        self.qlmt = QuanLyMuonTra()
        data = self.qlmt.fetch_all_mt()
        self.tableWidget.setRowCount(0)
        for row_number, row_data in enumerate(data):
            self.tableWidget.insertRow(row_number)
            for column_number, data in enumerate(row_data):
                self.tableWidget.setItem(row_number, column_number, QtWidgets.QTableWidgetItem(str(data)))

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setToolTip(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">Thông tin mượn trả</span></p></body></html>"))
        self.btnAdd.setText(_translate("Form", "Thêm"))
        self.btnXoa.setText(_translate("Form", "Xóa"))
        self.btnSua.setText(_translate("Form", "Sửa"))
        self.label_9.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Mã mượn trả :</span></p></body></html>"))
        self.label_10.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Mã KH :</span></p></body></html>"))
        self.label_11.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Mã DV :</span></p></body></html>"))
        self.comboBox.setItemText(0, _translate("Form", "Đã mượn "))
        self.comboBox.setItemText(1, _translate("Form", "Đã trả"))
        self.comboBox.setItemText(2, _translate("Form", "Chưa trả"))
        self.label_14.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Trạng thái :</span></p></body></html>"))
        self.label_13.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Ngày trả :</span></p></body></html>"))
        self.label_12.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Ngày mượn :</span></p></body></html>"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Mã mượn trả"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Mã KH"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Mã DV"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Ngày mượn"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Ngày trả"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Trạng thái"))

    def add_mt(self):
        try:
            mamt = self.lineEdit_6.text()
            idkhachhang = self.lineEdit_2.text()
            ma_dv = self.lineEdit_3.text()
            ngaymuon = self.dateEdit.date().toString("yyyy-MM-dd")
            ngaytra = self.dateEdit_2.date().toString("yyyy-MM-dd")
            trangthai = self.comboBox.currentText()
            self.qlmt.add_mt(mamt, idkhachhang, ma_dv, ngaymuon, ngaytra, trangthai)
            self.load_data()
            if not mamt or not idkhachhang or not ma_dv or not ngaymuon or not ngaytra or not trangthai:
                QtWidgets.QMessageBox.critical(None, 'Error', 'Vui lòng nhập đầy đủ thông tin')
                return
            
            QuanLyMuonTra().add_mt(mamt, idkhachhang, ma_dv, ngaymuon, ngaytra, trangthai)
            QtWidgets.QMessageBox.information(None, 'Thông báo', 'Thêm thông tin thành công')
            self.load_data()
        except Exception as e:
            QtWidgets.QMessageBox.critical(None, 'Error', 'Thêm thông tin thất bại')
            print(e)

    def delete_mt(self):
        try:
            mamt = self.lineEdit_6.text()
            self.qlmt.delete_mt(mamt)
            self.load_data()
            if not mamt:
                QtWidgets.QMessageBox.critical(None, 'Error', 'Vui lòng nhập mã mượn trả')
                return
            QuanLyMuonTra().delete_mt(mamt)
            QtWidgets.QMessageBox.information(None, 'Thông báo', 'Xóa thông tin thành công')
            self.load_data()
        except Exception as e:
            QtWidgets.QMessageBox.critical(None, 'Error', 'Xóa thông tin thất bại')
            print(e)

    def update_mt(self):
        try:
            mamt = self.lineEdit_6.text()
            idkhachhang = self.lineEdit_2.text()
            ma_dv = self.lineEdit_3.text()
            ngaymuon = self.dateEdit.date().toString("yyyy-MM-dd")
            ngaytra = self.dateEdit_2.date().toString("yyyy-MM-dd")
            trangthai = self.comboBox.currentText()
            self.qlmt.update_mt(mamt, idkhachhang, ma_dv, ngaymuon, ngaytra, trangthai)
            self.load_data()
            if not mamt or not idkhachhang or not ma_dv or not ngaymuon or not ngaytra or not trangthai:
                QtWidgets.QMessageBox.critical(None, 'Error', 'Vui lòng nhập đầy đủ thông tin')
                return
            QuanLyMuonTra().update_mt(mamt, idkhachhang, ma_dv, ngaymuon, ngaytra, trangthai)
            QtWidgets.QMessageBox.information(None, 'Thông báo', 'Sửa thông tin thành công')
            self.load_data()
        except Exception as e:
            QtWidgets.QMessageBox.critical(None, 'Error', 'Sửa thông tin thất bại')
            print(e)

    def cell_click(self, row, column):
        self.lineEdit_6.setText(self.tableWidget.item(row, 0).text())
        self.lineEdit_2.setText(self.tableWidget.item(row, 1).text())
        self.lineEdit_3.setText(self.tableWidget.item(row, 2).text())
        self.dateEdit.setDate(QtCore.QDate.fromString(self.tableWidget.item(row, 3).text(), "yyyy-MM-dd"))
        self.dateEdit_2.setDate(QtCore.QDate.fromString(self.tableWidget.item(row, 4).text(), "yyyy-MM-dd"))
        self.comboBox.setCurrentText(self.tableWidget.item(row, 5).text())


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
