# Form implementation generated from reading ui file 'QLBaogia.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from Database.DBConnect import DbManager
from Controller.qlcgdv import QLCGDV

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1020, 567)
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setGeometry(QtCore.QRect(350, 0, 311, 31))
        self.frame.setStyleSheet("background-color:rgb(170, 170, 255)")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(60, 0, 201, 31))
        self.label.setStyleSheet("font: 75 16pt \"Times New Roman\";")
        self.label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(parent=Form)
        self.tableWidget.setGeometry(QtCore.QRect(-10, 270, 1031, 321))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(0, 30, 1031, 241))
        self.widget.setStyleSheet("\n"
"background-color: rgb(206, 228, 255);")
        self.widget.setObjectName("widget")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 231, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 91, 21))
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(100, 50, 71, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setGeometry(QtCore.QRect(210, 50, 81, 21))
        self.label_4.setObjectName("label_4")
        self.comboBox = QtWidgets.QComboBox(parent=self.widget)
        self.comboBox.setGeometry(QtCore.QRect(330, 50, 121, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_5 = QtWidgets.QLabel(parent=self.widget)
        self.label_5.setGeometry(QtCore.QRect(750, 20, 141, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(610, 50, 381, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_6 = QtWidgets.QLabel(parent=self.widget)
        self.label_6.setGeometry(QtCore.QRect(20, 110, 91, 21))
        self.label_6.setObjectName("label_6")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_3.setGeometry(QtCore.QRect(100, 110, 71, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_7 = QtWidgets.QLabel(parent=self.widget)
        self.label_7.setGeometry(QtCore.QRect(220, 110, 91, 21))
        self.label_7.setObjectName("label_7")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_4.setGeometry(QtCore.QRect(330, 109, 121, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_5.setGeometry(QtCore.QRect(720, 130, 171, 61))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_8 = QtWidgets.QLabel(parent=self.widget)
        self.label_8.setGeometry(QtCore.QRect(770, 100, 101, 21))
        self.label_8.setObjectName("label_8")
        self.btnTinh = QtWidgets.QPushButton(parent=self.widget)
        self.btnTinh.setGeometry(QtCore.QRect(610, 150, 61, 31))
        self.btnTinh.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.btnTinh.setObjectName("btnTinh")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.btnTinh.clicked.connect(self.tinh)
        self.tableWidget.cellClicked.connect(self.display_record)
        self.load_data()


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setToolTip(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">BÁO GIÁ</span></p></body></html>"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Mã dịch vụ"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Gói dịch vụ"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Mô tả gói dịch vụ"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Giá tiền"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Chi tiết báo giá :</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Mã DV:</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">Gói Dịch Vụ</span></p></body></html>"))
        self.comboBox.setItemText(0, _translate("Form", "Chụp hình cưới"))
        self.comboBox.setItemText(1, _translate("Form", "Cho thuê áo cưới"))
        self.comboBox.setItemText(2, _translate("Form", "Dịch vụ khác"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt;\">Mô tả gói dịch vụ</span></p></body></html>"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Giá tiền:</span></p><p><br/></p></body></html>"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Phụ thu thêm:</span></p><p><br/></p></body></html>"))
        self.label_8.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Tổng số tiền:</span></p></body></html>"))
        self.btnTinh.setText(_translate("Form", "TÍNH"))
    def load_data(self):
        try:
            quanlycacgoidv = QLCGDV()
            result = quanlycacgoidv.fetch_all_dv()
            self.tableWidget.setRowCount(0)
            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number, column_number, QtWidgets.QTableWidgetItem(str(data)))
        except Exception as e:
            QtWidgets.QMessageBox.critical(None, 'Error', str(e))
    def tinh(self):
        try:
            phuthu = self.lineEdit_4.text()
            gia = self.lineEdit_3.text()
            tong = int(gia) + int(phuthu)
            self.lineEdit_5.setText(str(tong))
        except Exception as e:
            QtWidgets.QMessageBox.critical(None, 'Error', str(e))
    def display_record(self, row):
        self.lineEdit.setText(self.tableWidget.item(row, 0).text())
        self.comboBox.setCurrentText(self.tableWidget.item(row, 1).text())
        self.lineEdit_3.setText(self.tableWidget.item(row, 3).text())
        self.lineEdit_2.setText(self.tableWidget.item(row, 2).text())


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
