# Form implementation generated from reading ui file 'QLLichHen.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets
from Controller.quanlylichhen import QLLH
from PyQt6.QtWidgets import QTableWidgetItem


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(663, 514)
        Form.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setGeometry(QtCore.QRect(190, 10, 311, 31))
        self.frame.setStyleSheet("background-color:rgb(170, 170, 255)")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(70, 0, 201, 31))
        self.label_2.setStyleSheet("font: 75 16pt \"Times New Roman\";")
        self.label_2.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 141, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(60, 80, 91, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setGeometry(QtCore.QRect(60, 120, 61, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=Form)
        self.label_6.setGeometry(QtCore.QRect(60, 160, 71, 21))
        self.label_6.setObjectName("label_6")
        self.dateEdit_2 = QtWidgets.QDateEdit(parent=Form)
        self.dateEdit_2.setGeometry(QtCore.QRect(150, 160, 111, 22))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.label_7 = QtWidgets.QLabel(parent=Form)
        self.label_7.setGeometry(QtCore.QRect(370, 80, 61, 21))
        self.label_7.setObjectName("label_7")
        self.label_10 = QtWidgets.QLabel(parent=Form)
        self.label_10.setGeometry(QtCore.QRect(370, 120, 61, 21))
        self.label_10.setObjectName("label_10")
        self.btnAddLH = QtWidgets.QPushButton(parent=Form)
        self.btnAddLH.setGeometry(QtCore.QRect(150, 210, 61, 31))
        self.btnAddLH.setStyleSheet("""
            background-color: rgb(213, 236, 255);
            border: 2px solid rgb(100, 150, 255);
            border-radius: 5px;
            padding: 5px;
            font: 10pt "Arial";
            box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.2);
        """)
        self.btnAddLH.setObjectName("btnAddLH")
        self.btnAddLH_3 = QtWidgets.QPushButton(parent=Form)
        self.btnAddLH_3.setGeometry(QtCore.QRect(400, 210, 61, 31))
        self.btnAddLH_3.setStyleSheet("""
            background-color: rgb(213, 236, 255);
            border: 2px solid rgb(100, 150, 255);
            border-radius: 5px;
            padding: 5px;
            font: 10pt "Arial";
            box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.2);
        """)
        self.btnAddLH_3.setObjectName("btnAddLH_3")
        self.btnAddLH_2 = QtWidgets.QPushButton(parent=Form)
        self.btnAddLH_2.setGeometry(QtCore.QRect(280, 210, 61, 31))
        self.btnAddLH_2.setStyleSheet("""
            background-color: rgb(213, 236, 255);
            border: 2px solid rgb(100, 150, 255);
            border-radius: 5px;
            padding: 5px;
            font: 10pt "Arial";
            box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.2);
        """)
        self.btnAddLH_2.setObjectName("btnAddLH_2")
        self.comboBox = QtWidgets.QComboBox(parent=Form)
        self.comboBox.setGeometry(QtCore.QRect(450, 160, 151, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_11 = QtWidgets.QLabel(parent=Form)
        self.label_11.setGeometry(QtCore.QRect(370, 160, 61, 21))
        self.label_11.setObjectName("label_11")
        self.lineEdit = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit.setGeometry(QtCore.QRect(150, 80, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(150, 120, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(450, 120, 151, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(450, 80, 151, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(-1, 280, 671, 241))
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget.setObjectName("widget")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.widget)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 671, 231))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.btnAddLH.clicked.connect(self.addLH)
        self.btnAddLH_2.clicked.connect(self.updateLH)
        self.btnAddLH_3.clicked.connect(self.deleteLH)
        self.tableWidget.cellClicked.connect(self.cellClick)
        self.loadLH()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setToolTip(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">QUẢN LÝ LỊCH HẸN</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Chi tiết nhân viên</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Mã lịch hẹn :</span></p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Tên KH</span></p></body></html>"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Ngày hẹn :</span></p><p><span style=\" font-size:9pt;\"><br/></span></p></body></html>"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">SDT :</span></p></body></html>"))
        self.label_10.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Địa Chỉ :</span></p></body></html>"))
        self.btnAddLH.setText(_translate("Form", "Thêm "))
        self.btnAddLH_3.setText(_translate("Form", "Xóa "))
        self.btnAddLH_2.setText(_translate("Form", "Sửa "))
        self.comboBox.setItemText(0, _translate("Form", "Đã đặt"))
        self.comboBox.setItemText(1, _translate("Form", "Đã đến"))
        self.comboBox.setItemText(2, _translate("Form", "Quá hẹn"))
        self.label_11.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Trạng thái:</span></p></body></html>"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Mã lịch hẹn"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Tên KH"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "SĐT"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Địa chỉ "))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Ngày hẹn"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Trạng thái"))

    def loadLH(self):
        self.tableWidget.setRowCount(0)
        lh = QLLH().fetch_all_lh()
        for row_number, row_data in enumerate(lh):
            self.tableWidget.insertRow(row_number)
            for column_number, data in enumerate(row_data):
                self.tableWidget.setItem(row_number, column_number, QtWidgets.QTableWidgetItem(str(data)))

    def addLH(self):
        try:
            malh = self.lineEdit.text()
            tenkh = self.lineEdit_2.text()
            sdt = self.lineEdit_4.text()
            diachi = self.lineEdit_3.text()
            ngayhen = self.dateEdit_2.date().toString("yyyy-MM-dd")
            trangthai = self.comboBox.currentText()
            if not malh or not tenkh or not sdt or not diachi or not ngayhen or not trangthai:
                QtWidgets.QMessageBox.critical(None, "Error", "Vui lòng nhập đầy đủ thông tin")
                return
            QLLH().add_lh(malh, tenkh, sdt, diachi, ngayhen, trangthai)
            QtWidgets.QMessageBox.information(None, "Success", "Add lịch hẹn thành công")
            self.loadLH()
        except Exception as e:
            QtWidgets.QMessageBox.critical(None, "Error", str(e))

    def updateLH(self):
        try:
            malh = self.lineEdit.text()
            tenkh = self.lineEdit_2.text()
            sdt = self.lineEdit_4.text()
            diachi = self.lineEdit_3.text()
            ngayhen = self.dateEdit_2.date().toString("yyyy-MM-dd")
            trangthai = self.comboBox.currentText()
            if not malh or not tenkh or not sdt or not diachi or not ngayhen or not trangthai:
                QtWidgets.QMessageBox.critical(None, "Error", "Vui lòng nhập đầy đủ thông tin")
                return
            QLLH().update_lh(malh, tenkh, sdt, diachi, ngayhen, trangthai)
            QtWidgets.QMessageBox.information(None, "Success", "Update lịch hẹn thành công")
            self.loadLH()
        except Exception as e:
            QtWidgets.QMessageBox.critical(None, "Error", str(e))

    def deleteLH(self):
        try:
            malh = self.lineEdit.text()
            if not malh:
                QtWidgets.QMessageBox.critical(None, "Error", "Vui lòng chọn lịch hẹn cần xóa")
                return
            QLLH().delete_lh(malh)
            QtWidgets.QMessageBox.information(None, "Success", "Delete lịch hẹn thành công")
            self.loadLH()
        except Exception as e:
            QtWidgets.QMessageBox.critical(None, "Error", str(e))

    def cellClick(self, row, column):
        self.lineEdit.setText(self.tableWidget.item(row, 0).text())
        self.lineEdit_2.setText(self.tableWidget.item(row, 1).text())
        self.lineEdit_4.setText(self.tableWidget.item(row, 2).text())
        self.lineEdit_3.setText(self.tableWidget.item(row, 3).text())
        self.dateEdit_2.setDate(QtCore.QDate.fromString(self.tableWidget.item(row, 4).text(), "yyyy-MM-dd"))
        self.comboBox.setCurrentText(self.tableWidget.item(row, 5).text())
        self.loadLH()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
